add Azure provider
Kuadrant/dns-operator pull request #184
Opened 2024-07-09 12:23 UTC by philbrookes

2024-07-10 09:03 UTC, mikenairn commented on test/e2e/multi_record_test.go
> +				return
```suggestion
				Skip("not supported for Azure provider")
```

2024-07-10 17:38 UTC, mikenairn requested changes
Left some comments.

Can you add "azure" [here](https://github.com/Kuadrant/dns-operator/blob/main/config/deploy/local/kustomization.yaml#L13) so that it gets enabled on the local deployments (make local-setup(-multi) DEPLOY=true)
```
value: --provider=aws,google,azure,inmemory
```

Can you also add the azure import [here](https://github.com/Kuadrant/dns-operator/blob/main/test/e2e/multi_instance/suite_test.go#L28), and add a skip on the loadbalanced test in there also.
```
_ "github.com/kuadrant/dns-operator/internal/provider/azure"
```

Are you adding azure to the GH action e2e tests in this PR or doing that in another? Probably good to add it sooner rather than later, will require a new dns zone and principal etc.. setup in Azure and credentials added in GitHub.

2024-07-11 07:34 UTC, philbrookes commented on README.md
> +make local-setup-azure-mz-clean local-setup-azure-mz-generate KUADRANT_AZURE_CREDENTIALS='<My Azure Credentials.json>' KUADRANT_AZURE_DNS_ZONE_ID=<My Azure Zone ID>
yeah, the ID is pretty gross, I couldn't see an obvious way to shorten it, due to the variable resourceGroup.

2024-07-12 10:15 UTC, mikenairn commented on .github/workflows/ci-e2e.yaml
> +          make local-setup-azure-mz-clean local-setup-azure-mz-generate KUADRANT_AZURE_DNS_ZONE_ID='${{ secret.E2E_AZURE_ZONE_ID }}' KUADRANT_AZURE_ZONE_ROOT_DOMAIN=e2e.azure.hcpapps.net KUADRANT_AZU
```suggestion
          make local-setup-azure-mz-clean local-setup-azure-mz-generate KUADRANT_AZURE_DNS_ZONE_ID='${{ secrets.E2E_AZURE_ZONE_ID }}' KUADRANT_AZURE_ZONE_ROOT_DOMAIN=e2e.azure.hcpapps.net KUADRANT_AZURE_CREDENTIALS='${{ secrets.E2E_AZURE_CREDENTIALS }}'
```

2024-07-16 07:59 UTC, mikenairn approved these changes

2024-07-16 08:04 UTC, merged